
#  SOIL_FOUND - system has SOIL
#  SOIL_INCLUDE_DIR - the SOIL include directory
#  SOIL_LIBRARY - Link these to use SOIL
#  SOIL_LIBRARIES

  

find_path (SOIL_INCLUDE_DIR NAMES SOIL.h
  HINTS
  $ENV{DEPENDENCY_PATH}/include
  PATHS ${SOIL_SEARCH_PATHS}
)
 
find_library (SOIL_LIBRARY_DEBUG NAMES soild 

  HINTS
  $ENV{DEPENDENCY_PATH}/lib

  PATHS ${SOIL_SEARCH_PATHS}
)

find_library (SOIL_LIBRARY_RELEASE NAMES soil 
  HINTS
  $ENV{DEPENDENCY_PATH}/lib

  PATHS ${SOIL_SEARCH_PATHS}
)

if (SOIL_INCLUDE_DIR AND SOIL_LIBRARY_RELEASE)
  set(SOIL_FOUND TRUE)
endif()

if (SOIL_LIBRARY_RELEASE)
    set (SOIL_LIBRARIES ${SOIL_LIBRARY_RELEASE})
endif()

if (SOIL_LIBRARY_DEBUG AND SOIL_LIBRARY_RELEASE)
    set (SOIL_LIBRARIES debug ${SOIL_LIBRARY_DEBUG} optimized ${SOIL_LIBRARY_RELEASE} )
endif()


if (SOIL_FOUND)
  MESSAGE("-- Found SOIL ${SOIL_LIBRARIES}")
  mark_as_advanced (SOIL_INCLUDE_DIR SOIL_LIBRARY SOIL_LIBRARIES)
endif()
